import type { DocumentModel, Page } from '../types/document';
import { generateId } from '../utils/id';

export const CURRENT_DOCUMENT_VERSION = 2;

export function createDefaultDocument(): DocumentModel {
  const page1Id = generateId('page');
  const frame1Id = generateId('frame');

  const defaultPage: Page = {
    id: page1Id,
    name: 'Page 1',
    objects: [
      {
        id: frame1Id,
        name: 'Mobile Canvas',
        type: 'frame',
        x: 100,
        y: 80,
        width: 380,
        height: 600,
        rotation: 0,
        opacity: 100,
        visible: true,
        locked: false,
        parentId: null,
        fill: '#181b24',
        stroke: '#2e3444',
        strokeWidth: 1,
        strokeOpacity: 100,
        cornerRadius: 24,
        clipsContent: true,
      },
      {
        id: generateId('rect'),
        name: 'Header Card',
        type: 'rectangle',
        x: 120,
        y: 110,
        width: 340,
        height: 160,
        rotation: 0,
        opacity: 100,
        visible: true,
        locked: false,
        parentId: frame1Id,
        fill: '#3b82f6',
        stroke: '#60a5fa',
        strokeWidth: 1,
        strokeOpacity: 100,
        cornerRadius: 16,
      },
      {
        id: generateId('text'),
        name: 'Card Title',
        type: 'text',
        x: 140,
        y: 135,
        width: 260,
        height: 32,
        rotation: 0,
        opacity: 100,
        visible: true,
        locked: false,
        parentId: frame1Id,
        content: 'Sagar Design Studio',
        fontSize: 22,
        fontWeight: 700,
        fontFamily: 'Inter, system-ui, sans-serif',
        fill: '#ffffff',
        textAlign: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
        autoResize: 'auto-height',
      },
      {
        id: generateId('text'),
        name: 'Card Subtitle',
        type: 'text',
        x: 140,
        y: 175,
        width: 290,
        height: 48,
        rotation: 0,
        opacity: 90,
        visible: true,
        locked: false,
        parentId: frame1Id,
        content: 'Infinite canvas with vector shapes, layers, frames, undo/redo & real-time properties.',
        fontSize: 13,
        fontWeight: 400,
        fontFamily: 'Inter, system-ui, sans-serif',
        fill: '#dbeafe',
        textAlign: 'left',
        lineHeight: 1.4,
        letterSpacing: 0,
        autoResize: 'auto-height',
      },
      {
        id: generateId('rect'),
        name: 'Action Button',
        type: 'rectangle',
        x: 120,
        y: 295,
        width: 340,
        height: 52,
        rotation: 0,
        opacity: 100,
        visible: true,
        locked: false,
        parentId: frame1Id,
        fill: '#10b981',
        stroke: '#34d399',
        strokeWidth: 1,
        strokeOpacity: 100,
        cornerRadius: 12,
      },
      {
        id: generateId('text'),
        name: 'Button Label',
        type: 'text',
        x: 230,
        y: 310,
        width: 120,
        height: 24,
        rotation: 0,
        opacity: 100,
        visible: true,
        locked: false,
        parentId: frame1Id,
        content: 'Get Started',
        fontSize: 15,
        fontWeight: 600,
        fontFamily: 'Inter, system-ui, sans-serif',
        fill: '#ffffff',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        autoResize: 'auto-width',
      },
      {
        id: generateId('ellipse'),
        name: 'Indicator Badge',
        type: 'ellipse',
        x: 120,
        y: 375,
        width: 56,
        height: 56,
        rotation: 0,
        opacity: 100,
        visible: true,
        locked: false,
        parentId: frame1Id,
        fill: '#8b5cf6',
        stroke: '#a78bfa',
        strokeWidth: 2,
        strokeOpacity: 100,
      },
      {
        id: generateId('polygon'),
        name: 'Feature Star',
        type: 'polygon',
        x: 200,
        y: 375,
        width: 56,
        height: 56,
        rotation: 0,
        opacity: 100,
        visible: true,
        locked: false,
        parentId: frame1Id,
        points: 5,
        isStar: true,
        starRatio: 0.5,
        fill: '#f59e0b',
        stroke: '#fbbf24',
        strokeWidth: 1,
        strokeOpacity: 100,
      },
      {
        id: generateId('line'),
        name: 'Divider',
        type: 'line',
        x: 120,
        y: 460,
        width: 340,
        height: 0,
        rotation: 0,
        opacity: 60,
        visible: true,
        locked: false,
        parentId: frame1Id,
        stroke: '#475569',
        strokeWidth: 2,
        strokeOpacity: 100,
      },
      {
        id: generateId('text'),
        name: 'Footer Text',
        type: 'text',
        x: 120,
        y: 485,
        width: 340,
        height: 24,
        rotation: 0,
        opacity: 70,
        visible: true,
        locked: false,
        parentId: frame1Id,
        content: 'Press V for Select, R for Rectangle, T for Text, P for Polygon',
        fontSize: 12,
        fontWeight: 400,
        fontFamily: 'Inter, system-ui, sans-serif',
        fill: '#94a3b8',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        autoResize: 'auto-width',
      },
    ],
  };

  return {
    version: CURRENT_DOCUMENT_VERSION,
    id: generateId('doc'),
    name: 'Untitled Design',
    pages: [defaultPage],
    activePageId: page1Id,
    assets: {},
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}
