import type {
  DocumentModel,
  Page,
  FrameObject,
  TextObject,
  ComponentDefinition,
  ComponentSet,
  SceneObject,
  PrototypeDocumentData,
} from '../types/document';
import { generateId } from '../utils/id';
import { recomputePageLayout } from '../layout/layoutEngine';
import { createDefaultStyles } from '../system/styleEngine';
import { createDefaultVariables } from '../system/variableEngine';

export const CURRENT_DOCUMENT_VERSION = 5;

export function createDefaultDocument(): DocumentModel {
  const page1Id = generateId('page');
  const defaultStyles = createDefaultStyles();
  const defaultVars = createDefaultVariables();

  const components: Record<string, ComponentDefinition> = {};
  const componentSets: Record<string, ComponentSet> = {};
  const objects: SceneObject[] = [];

  // ==========================================
  // 1. BUTTON MASTER COMPONENTS
  // ==========================================
  const btnSetId = 'set_button';
  const btnPrimaryId = 'comp_btn_primary';
  const btnSecondaryId = 'comp_btn_secondary';
  const btnDestructiveId = 'comp_btn_destructive';

  const btnPrimaryRootId = generateId('frame');
  const btnPrimaryLabelId = generateId('text');
  const btnSecondaryRootId = generateId('frame');
  const btnSecondaryLabelId = generateId('text');
  const btnDestructiveRootId = generateId('frame');
  const btnDestructiveLabelId = generateId('text');

  // Master: Primary Button
  const masterBtnPrimary: FrameObject = {
    id: btnPrimaryRootId,
    name: 'Button / Primary',
    type: 'frame',
    x: 80,
    y: 100,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: btnPrimaryId,
    fill: '#6366f1',
    fillVariableId: 'var_brand_primary',
    fillStyleId: 'style_color_primary',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const masterBtnPrimaryLabel: TextObject = {
    id: btnPrimaryLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 60,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: btnPrimaryRootId,
    content: 'Get Started',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  // Master: Secondary Button
  const masterBtnSecondary: FrameObject = {
    id: btnSecondaryRootId,
    name: 'Button / Secondary',
    type: 'frame',
    x: 240,
    y: 100,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: btnSecondaryId,
    fill: '#1e293b',
    stroke: '#334155',
    strokeWidth: 1,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const masterBtnSecondaryLabel: TextObject = {
    id: btnSecondaryLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 60,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: btnSecondaryRootId,
    content: 'Learn More',
    fontSize: 14,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#f8fafc',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  // Master: Destructive Button
  const masterBtnDestructive: FrameObject = {
    id: btnDestructiveRootId,
    name: 'Button / Destructive',
    type: 'frame',
    x: 400,
    y: 100,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: btnDestructiveId,
    fill: '#ef4444',
    fillStyleId: 'style_color_danger',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const masterBtnDestructiveLabel: TextObject = {
    id: btnDestructiveLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 60,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: btnDestructiveRootId,
    content: 'Delete',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  components[btnPrimaryId] = {
    id: btnPrimaryId,
    name: 'Button / Primary',
    category: 'Buttons',
    rootObjectId: btnPrimaryRootId,
    componentSetId: btnSetId,
    variantProperties: { Variant: 'Primary' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  components[btnSecondaryId] = {
    id: btnSecondaryId,
    name: 'Button / Secondary',
    category: 'Buttons',
    rootObjectId: btnSecondaryRootId,
    componentSetId: btnSetId,
    variantProperties: { Variant: 'Secondary' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  components[btnDestructiveId] = {
    id: btnDestructiveId,
    name: 'Button / Destructive',
    category: 'Buttons',
    rootObjectId: btnDestructiveRootId,
    componentSetId: btnSetId,
    variantProperties: { Variant: 'Destructive' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  componentSets[btnSetId] = {
    id: btnSetId,
    name: 'Button',
    category: 'Buttons',
    variantPropertyNames: ['Variant'],
    componentIds: [btnPrimaryId, btnSecondaryId, btnDestructiveId],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  objects.push(
    masterBtnPrimary,
    masterBtnPrimaryLabel,
    masterBtnSecondary,
    masterBtnSecondaryLabel,
    masterBtnDestructive,
    masterBtnDestructiveLabel
  );

  // ==========================================
  // 2. CONNECTED PROTOTYPE SCREENS (6 Screens Scenario)
  // ==========================================

  // --- SCREEN 1: LANDING ---
  const screen1Id = 'screen_landing';
  const s1HeaderId = generateId('frame');
  const s1LogoId = generateId('text');
  const s1NavLinksId = generateId('frame');
  const s1NavLinkFeaturesId = generateId('text');
  const s1NavLinkPricingId = generateId('text');
  const s1NavLinkLoginId = generateId('text');
  const s1HeroId = generateId('frame');
  const s1HeadingId = generateId('text');
  const s1SubheadingId = generateId('text');
  const s1CtaBtnId = generateId('frame');
  const s1CtaBtnLabelId = generateId('text');

  const screen1: FrameObject = {
    id: screen1Id,
    name: '1. Landing Screen',
    type: 'frame',
    x: 60,
    y: 200,
    width: 960,
    height: 640,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    fill: '#0f131c',
    fillVariableId: 'var_bg_surface',
    cornerRadius: 16,
    clipsContent: true,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'stretch',
    padding: { top: 24, right: 32, bottom: 24, left: 32 },
    itemSpacing: 32,
    sizingHorizontal: 'fixed',
    sizingVertical: 'fixed',
  };

  const s1Header: FrameObject = {
    id: s1HeaderId,
    name: 'Landing Header',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 56,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen1Id,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'center',
    padding: { top: 12, right: 20, bottom: 12, left: 20 },
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s1Logo: TextObject = {
    id: s1LogoId,
    name: 'Logo',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s1HeaderId,
    content: '❖ BANAVA',
    fontSize: 16,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s1NavLinks: FrameObject = {
    id: s1NavLinksId,
    name: 'Nav Links Bar',
    type: 'frame',
    x: 0,
    y: 0,
    width: 280,
    height: 32,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s1HeaderId,
    fill: 'transparent',
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'end',
    counterAxisAlignItems: 'center',
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    itemSpacing: 20,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const s1NavLinkFeatures: TextObject = {
    id: s1NavLinkFeaturesId,
    name: 'Link Features',
    type: 'text',
    x: 0,
    y: 0,
    width: 60,
    height: 20,
    rotation: 0,
    opacity: 90,
    visible: true,
    locked: false,
    parentId: s1NavLinksId,
    content: 'Features',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#cbd5e1',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s1NavLinkPricing: TextObject = {
    id: s1NavLinkPricingId,
    name: 'Link Pricing',
    type: 'text',
    x: 0,
    y: 0,
    width: 50,
    height: 20,
    rotation: 0,
    opacity: 90,
    visible: true,
    locked: false,
    parentId: s1NavLinksId,
    content: 'Pricing',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#cbd5e1',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s1NavLinkLogin: TextObject = {
    id: s1NavLinkLoginId,
    name: 'Link Login',
    type: 'text',
    x: 0,
    y: 0,
    width: 50,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s1NavLinksId,
    content: 'Login →',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  const s1Hero: FrameObject = {
    id: s1HeroId,
    name: 'Hero Section',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 380,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen1Id,
    fill: 'transparent',
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 48, right: 0, bottom: 48, left: 0 },
    itemSpacing: 20,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s1Heading: TextObject = {
    id: s1HeadingId,
    name: 'Heading',
    type: 'text',
    x: 0,
    y: 0,
    width: 600,
    height: 52,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s1HeroId,
    content: 'Interactive UI Design Platform',
    fontSize: 38,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.1,
    letterSpacing: -0.5,
    autoResize: 'auto-width',
  };
  const s1Subheading: TextObject = {
    id: s1SubheadingId,
    name: 'Subheading',
    type: 'text',
    x: 0,
    y: 0,
    width: 520,
    height: 44,
    rotation: 0,
    opacity: 75,
    visible: true,
    locked: false,
    parentId: s1HeroId,
    content: 'Create high-fidelity interactive prototypes with smart animations, overlays, and device preview in BANAVA.',
    fontSize: 15,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'center',
    lineHeight: 1.4,
    letterSpacing: 0,
    autoResize: 'fixed',
  };
  const s1CtaBtn: FrameObject = {
    id: s1CtaBtnId,
    name: 'Explore Features CTA Button',
    type: 'frame',
    x: 0,
    y: 0,
    width: 180,
    height: 48,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s1HeroId,
    fill: '#6366f1',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 12, right: 24, bottom: 12, left: 24 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const s1CtaBtnLabel: TextObject = {
    id: s1CtaBtnLabelId,
    name: 'CTA Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 130,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s1CtaBtnId,
    content: 'Explore Features →',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  objects.push(
    screen1,
    s1Header,
    s1Logo,
    s1NavLinks,
    s1NavLinkFeatures,
    s1NavLinkPricing,
    s1NavLinkLogin,
    s1Hero,
    s1Heading,
    s1Subheading,
    s1CtaBtn,
    s1CtaBtnLabel
  );

  // --- SCREEN 2: FEATURES ---
  const screen2Id = 'screen_features';
  const s2HeaderId = generateId('frame');
  const s2BackBtnId = generateId('text');
  const s2TitleId = generateId('text');
  const s2CtaPricingId = generateId('frame');
  const s2CtaPricingLabelId = generateId('text');
  const s2FeaturesGridId = generateId('frame');
  const s2Card1Id = generateId('frame');
  const s2Card1TitleId = generateId('text');
  const s2Card2Id = generateId('frame');
  const s2Card2TitleId = generateId('text');

  const screen2: FrameObject = {
    id: screen2Id,
    name: '2. Features Screen',
    type: 'frame',
    x: 1080,
    y: 200,
    width: 960,
    height: 640,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    fill: '#0f131c',
    cornerRadius: 16,
    clipsContent: true,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'stretch',
    padding: { top: 24, right: 32, bottom: 24, left: 32 },
    itemSpacing: 28,
  };
  const s2Header: FrameObject = {
    id: s2HeaderId,
    name: 'Features Header',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 56,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen2Id,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'center',
    padding: { top: 12, right: 20, bottom: 12, left: 20 },
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s2BackBtn: TextObject = {
    id: s2BackBtnId,
    name: 'Back Button',
    type: 'text',
    x: 0,
    y: 0,
    width: 80,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2HeaderId,
    content: '← Back',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s2Title: TextObject = {
    id: s2TitleId,
    name: 'Screen Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2HeaderId,
    content: 'Platform Features',
    fontSize: 16,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s2CtaPricing: FrameObject = {
    id: s2CtaPricingId,
    name: 'Pricing CTA',
    type: 'frame',
    x: 0,
    y: 0,
    width: 120,
    height: 36,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2HeaderId,
    fill: '#6366f1',
    cornerRadius: 6,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 6, right: 14, bottom: 6, left: 14 },
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const s2CtaPricingLabel: TextObject = {
    id: s2CtaPricingLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 90,
    height: 18,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2CtaPricingId,
    content: 'View Pricing →',
    fontSize: 12,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  const s2FeaturesGrid: FrameObject = {
    id: s2FeaturesGridId,
    name: 'Features Grid',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 280,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen2Id,
    fill: 'transparent',
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'stretch',
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    itemSpacing: 24,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s2Card1: FrameObject = {
    id: s2Card1Id,
    name: 'Feature Card 1',
    type: 'frame',
    x: 0,
    y: 0,
    width: 436,
    height: 240,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2FeaturesGridId,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 32, right: 24, bottom: 32, left: 24 },
    itemSpacing: 12,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s2Card1Title: TextObject = {
    id: s2Card1TitleId,
    name: 'Card Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 300,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2Card1Id,
    content: 'Smart Animate & Transitions',
    fontSize: 18,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s2Card2: FrameObject = {
    id: s2Card2Id,
    name: 'Feature Card 2',
    type: 'frame',
    x: 0,
    y: 0,
    width: 436,
    height: 240,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2FeaturesGridId,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 32, right: 24, bottom: 32, left: 24 },
    itemSpacing: 12,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s2Card2Title: TextObject = {
    id: s2Card2TitleId,
    name: 'Card Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 300,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s2Card2Id,
    content: 'Modal Overlays & Backdrops',
    fontSize: 18,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  objects.push(
    screen2,
    s2Header,
    s2BackBtn,
    s2Title,
    s2CtaPricing,
    s2CtaPricingLabel,
    s2FeaturesGrid,
    s2Card1,
    s2Card1Title,
    s2Card2,
    s2Card2Title
  );

  // --- SCREEN 3: PRICING ---
  const screen3Id = 'screen_pricing';
  const s3HeaderId = generateId('frame');
  const s3BackBtnId = generateId('text');
  const s3TitleId = generateId('text');
  const s3TierCardId = generateId('frame');
  const s3TierTitleId = generateId('text');
  const s3TierPriceId = generateId('text');
  const s3GetStartedBtnId = generateId('frame');
  const s3GetStartedLabelId = generateId('text');

  const screen3: FrameObject = {
    id: screen3Id,
    name: '3. Pricing Screen',
    type: 'frame',
    x: 2100,
    y: 200,
    width: 960,
    height: 640,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    fill: '#0f131c',
    cornerRadius: 16,
    clipsContent: true,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'stretch',
    padding: { top: 24, right: 32, bottom: 24, left: 32 },
    itemSpacing: 36,
  };
  const s3Header: FrameObject = {
    id: s3HeaderId,
    name: 'Pricing Header',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 56,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen3Id,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'center',
    padding: { top: 12, right: 20, bottom: 12, left: 20 },
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s3BackBtn: TextObject = {
    id: s3BackBtnId,
    name: 'Back Button',
    type: 'text',
    x: 0,
    y: 0,
    width: 80,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s3HeaderId,
    content: '← Back',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s3Title: TextObject = {
    id: s3TitleId,
    name: 'Screen Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s3HeaderId,
    content: 'Choose a Plan',
    fontSize: 16,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'right',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  const s3TierCard: FrameObject = {
    id: s3TierCardId,
    name: 'Pro Plan Card',
    type: 'frame',
    x: 0,
    y: 0,
    width: 420,
    height: 320,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen3Id,
    fill: '#181e2e',
    stroke: '#6366f1',
    strokeWidth: 2,
    cornerRadius: 16,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 36, right: 32, bottom: 36, left: 32 },
    itemSpacing: 16,
    sizingHorizontal: 'fixed',
    sizingVertical: 'hug',
  };
  const s3TierTitle: TextObject = {
    id: s3TierTitleId,
    name: 'Tier Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 160,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s3TierCardId,
    content: 'Professional Plan',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s3TierPrice: TextObject = {
    id: s3TierPriceId,
    name: 'Price Tag',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 36,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s3TierCardId,
    content: '$29 / month',
    fontSize: 26,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s3GetStartedBtn: FrameObject = {
    id: s3GetStartedBtnId,
    name: 'Sign Up CTA Button',
    type: 'frame',
    x: 0,
    y: 0,
    width: 200,
    height: 48,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s3TierCardId,
    fill: '#6366f1',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 12, right: 24, bottom: 12, left: 24 },
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const s3GetStartedLabel: TextObject = {
    id: s3GetStartedLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 130,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s3GetStartedBtnId,
    content: 'Continue to Login →',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  objects.push(
    screen3,
    s3Header,
    s3BackBtn,
    s3Title,
    s3TierCard,
    s3TierTitle,
    s3TierPrice,
    s3GetStartedBtn,
    s3GetStartedLabel
  );

  // --- SCREEN 4: LOGIN ---
  const screen4Id = 'screen_login';
  const s4CardId = generateId('frame');
  const s4TitleId = generateId('text');
  const s4EmailInputId = generateId('frame');
  const s4EmailTextId = generateId('text');
  const s4SubmitBtnId = generateId('frame');
  const s4SubmitLabelId = generateId('text');
  const s4BackToHomeId = generateId('text');

  const screen4: FrameObject = {
    id: screen4Id,
    name: '4. Login Screen',
    type: 'frame',
    x: 3120,
    y: 200,
    width: 960,
    height: 640,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    fill: '#0f131c',
    cornerRadius: 16,
    clipsContent: true,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 80, right: 32, bottom: 80, left: 32 },
    itemSpacing: 24,
  };
  const s4Card: FrameObject = {
    id: s4CardId,
    name: 'Auth Container Card',
    type: 'frame',
    x: 0,
    y: 0,
    width: 380,
    height: 340,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen4Id,
    fill: '#181e2e',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 16,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'stretch',
    padding: { top: 32, right: 28, bottom: 32, left: 28 },
    itemSpacing: 16,
    sizingHorizontal: 'fixed',
    sizingVertical: 'hug',
  };
  const s4Title: TextObject = {
    id: s4TitleId,
    name: 'Sign In Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 200,
    height: 28,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s4CardId,
    content: 'Welcome to BANAVA',
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s4EmailInput: FrameObject = {
    id: s4EmailInputId,
    name: 'Email Input',
    type: 'frame',
    x: 0,
    y: 0,
    width: 324,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s4CardId,
    fill: '#0f172a',
    stroke: '#334155',
    strokeWidth: 1,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 14, bottom: 10, left: 14 },
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s4EmailText: TextObject = {
    id: s4EmailTextId,
    name: 'Placeholder',
    type: 'text',
    x: 0,
    y: 0,
    width: 160,
    height: 20,
    rotation: 0,
    opacity: 70,
    visible: true,
    locked: false,
    parentId: s4EmailInputId,
    content: 'designer@banava.io',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s4SubmitBtn: FrameObject = {
    id: s4SubmitBtnId,
    name: 'Submit Login Button',
    type: 'frame',
    x: 0,
    y: 0,
    width: 324,
    height: 46,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s4CardId,
    fill: '#6366f1',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 12, right: 20, bottom: 12, left: 20 },
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s4SubmitLabel: TextObject = {
    id: s4SubmitLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s4SubmitBtnId,
    content: 'Sign In to Dashboard →',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s4BackToHome: TextObject = {
    id: s4BackToHomeId,
    name: 'Home Link',
    type: 'text',
    x: 0,
    y: 0,
    width: 120,
    height: 18,
    rotation: 0,
    opacity: 80,
    visible: true,
    locked: false,
    parentId: s4CardId,
    content: '← Back to Home',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  objects.push(
    screen4,
    s4Card,
    s4Title,
    s4EmailInput,
    s4EmailText,
    s4SubmitBtn,
    s4SubmitLabel,
    s4BackToHome
  );

  // --- SCREEN 5: DASHBOARD ---
  const screen5Id = 'screen_dashboard';
  const s5HeaderId = generateId('frame');
  const s5LogoId = generateId('text');
  const s5SettingsTriggerBtnId = generateId('frame');
  const s5SettingsTriggerLabelId = generateId('text');
  const s5MetricsRowId = generateId('frame');
  const s5Metric1Id = generateId('frame');
  const s5Metric1ValId = generateId('text');
  const s5Metric1LabelId = generateId('text');
  const s5Metric2Id = generateId('frame');
  const s5Metric2ValId = generateId('text');
  const s5Metric2LabelId = generateId('text');

  const screen5: FrameObject = {
    id: screen5Id,
    name: '5. Dashboard Screen',
    type: 'frame',
    x: 4140,
    y: 200,
    width: 960,
    height: 640,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    fill: '#0f131c',
    cornerRadius: 16,
    clipsContent: true,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'stretch',
    padding: { top: 24, right: 32, bottom: 24, left: 32 },
    itemSpacing: 32,
  };
  const s5Header: FrameObject = {
    id: s5HeaderId,
    name: 'Dashboard Header',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 56,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen5Id,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'center',
    padding: { top: 12, right: 20, bottom: 12, left: 20 },
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s5Logo: TextObject = {
    id: s5LogoId,
    name: 'App Logo',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s5HeaderId,
    content: '❖ Workspace Hub',
    fontSize: 16,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s5SettingsTriggerBtn: FrameObject = {
    id: s5SettingsTriggerBtnId,
    name: 'Settings Overlay Trigger Button',
    type: 'frame',
    x: 0,
    y: 0,
    width: 150,
    height: 38,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s5HeaderId,
    fill: 'rgba(99, 102, 241, 0.2)',
    stroke: '#6366f1',
    strokeWidth: 1,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 8, right: 16, bottom: 8, left: 16 },
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const s5SettingsTriggerLabel: TextObject = {
    id: s5SettingsTriggerLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 110,
    height: 18,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s5SettingsTriggerBtnId,
    content: '⚙ Quick Settings',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#c084fc',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  const s5MetricsRow: FrameObject = {
    id: s5MetricsRowId,
    name: 'Metrics Container',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 180,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen5Id,
    fill: 'transparent',
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'stretch',
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    itemSpacing: 24,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s5Metric1: FrameObject = {
    id: s5Metric1Id,
    name: 'Metric Card 1',
    type: 'frame',
    x: 0,
    y: 0,
    width: 436,
    height: 160,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s5MetricsRowId,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 28, right: 20, bottom: 28, left: 20 },
    itemSpacing: 8,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s5Metric1Val: TextObject = {
    id: s5Metric1ValId,
    name: 'Value',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 38,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s5Metric1Id,
    content: '2,840',
    fontSize: 32,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s5Metric1Label: TextObject = {
    id: s5Metric1LabelId,
    name: 'Metric Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 160,
    height: 18,
    rotation: 0,
    opacity: 70,
    visible: true,
    locked: false,
    parentId: s5Metric1Id,
    content: 'Active Components in Library',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s5Metric2: FrameObject = {
    id: s5Metric2Id,
    name: 'Metric Card 2',
    type: 'frame',
    x: 0,
    y: 0,
    width: 436,
    height: 160,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s5MetricsRowId,
    fill: '#181e2e',
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 28, right: 20, bottom: 28, left: 20 },
    itemSpacing: 8,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const s5Metric2Val: TextObject = {
    id: s5Metric2ValId,
    name: 'Value',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 38,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s5Metric2Id,
    content: '60 FPS',
    fontSize: 32,
    fontWeight: 800,
    fontFamily: 'Inter, sans-serif',
    fill: '#34d399',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s5Metric2Label: TextObject = {
    id: s5Metric2LabelId,
    name: 'Metric Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 160,
    height: 18,
    rotation: 0,
    opacity: 70,
    visible: true,
    locked: false,
    parentId: s5Metric2Id,
    content: 'Real-time Prototype Engine',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  objects.push(
    screen5,
    s5Header,
    s5Logo,
    s5SettingsTriggerBtn,
    s5SettingsTriggerLabel,
    s5MetricsRow,
    s5Metric1,
    s5Metric1Val,
    s5Metric1Label,
    s5Metric2,
    s5Metric2Val,
    s5Metric2Label
  );

  // --- SCREEN 6: SETTINGS MODAL OVERLAY ---
  const screen6Id = 'screen_modal_settings';
  const s6TitleId = generateId('text');
  const s6DescId = generateId('text');
  const s6CloseBtnId = generateId('frame');
  const s6CloseLabelId = generateId('text');

  const screen6: FrameObject = {
    id: screen6Id,
    name: '6. Settings Modal Overlay',
    type: 'frame',
    x: 5160,
    y: 200,
    width: 520,
    height: 320,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    fill: '#1e293b',
    stroke: '#334155',
    strokeWidth: 1,
    cornerRadius: 16,
    clipsContent: true,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'stretch',
    padding: { top: 32, right: 32, bottom: 32, left: 32 },
    itemSpacing: 18,
  };
  const s6Title: TextObject = {
    id: s6TitleId,
    name: 'Modal Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 240,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen6Id,
    content: '⚙ System Preferences',
    fontSize: 18,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const s6Desc: TextObject = {
    id: s6DescId,
    name: 'Modal Description',
    type: 'text',
    x: 0,
    y: 0,
    width: 456,
    height: 36,
    rotation: 0,
    opacity: 75,
    visible: true,
    locked: false,
    parentId: screen6Id,
    content: 'Manage prototype presentation modes, device viewports, and animation timings.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'center',
    lineHeight: 1.4,
    letterSpacing: 0,
    autoResize: 'fixed',
  };
  const s6CloseBtn: FrameObject = {
    id: s6CloseBtnId,
    name: 'Save & Close Button',
    type: 'frame',
    x: 0,
    y: 0,
    width: 160,
    height: 42,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: screen6Id,
    fill: '#6366f1',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 20, bottom: 10, left: 20 },
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const s6CloseLabel: TextObject = {
    id: s6CloseLabelId,
    name: 'Close Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 120,
    height: 18,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: s6CloseBtnId,
    content: 'Done & Close ✕',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  objects.push(screen6, s6Title, s6Desc, s6CloseBtn, s6CloseLabel);

  // ==========================================
  // 3. PROTOTYPE FLOWS & INTERACTIONS CONFIG
  // ==========================================
  const defaultPrototype: PrototypeDocumentData = {
    flows: {
      'flow_landing': {
        id: 'flow_landing',
        name: 'Main Website Flow',
        startingPointId: screen1Id,
        description: 'Landing -> Features -> Pricing -> Login -> Dashboard',
      },
      'flow_dashboard': {
        id: 'flow_dashboard',
        name: 'Dashboard & Modal Flow',
        startingPointId: screen5Id,
        description: 'Dashboard screen with modal settings overlay',
      },
    },
    connections: {
      // 1. Landing -> Features
      'conn_1': {
        id: 'conn_1',
        sourceNodeId: s1CtaBtnId,
        sourceEvent: 'on-click',
        action: 'navigate-to',
        destinationNodeId: screen2Id,
        transition: { type: 'slide-in', duration: 300, easing: 'ease-out', direction: 'left' },
        enabled: true,
      },
      // 2. Landing Header Link -> Features
      'conn_2': {
        id: 'conn_2',
        sourceNodeId: s1NavLinkFeaturesId,
        sourceEvent: 'on-click',
        action: 'navigate-to',
        destinationNodeId: screen2Id,
        transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
        enabled: true,
      },
      // 3. Landing Header Link -> Pricing
      'conn_3': {
        id: 'conn_3',
        sourceNodeId: s1NavLinkPricingId,
        sourceEvent: 'on-click',
        action: 'navigate-to',
        destinationNodeId: screen3Id,
        transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
        enabled: true,
      },
      // 4. Landing Header Link -> Login
      'conn_4': {
        id: 'conn_4',
        sourceNodeId: s1NavLinkLoginId,
        sourceEvent: 'on-click',
        action: 'navigate-to',
        destinationNodeId: screen4Id,
        transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
        enabled: true,
      },
      // 5. Features -> Pricing
      'conn_5': {
        id: 'conn_5',
        sourceNodeId: s2CtaPricingId,
        sourceEvent: 'on-click',
        action: 'navigate-to',
        destinationNodeId: screen3Id,
        transition: { type: 'slide-in', duration: 300, easing: 'ease-out', direction: 'left' },
        enabled: true,
      },
      // 6. Pricing -> Login
      'conn_6': {
        id: 'conn_6',
        sourceNodeId: s3GetStartedBtnId,
        sourceEvent: 'on-click',
        action: 'navigate-to',
        destinationNodeId: screen4Id,
        transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
        enabled: true,
      },
      // 7. Login Submit -> Dashboard
      'conn_7': {
        id: 'conn_7',
        sourceNodeId: s4SubmitBtnId,
        sourceEvent: 'on-click',
        action: 'navigate-to',
        destinationNodeId: screen5Id,
        transition: { type: 'smart-animate', duration: 300, easing: 'ease-out' },
        enabled: true,
      },
      // 8. Dashboard -> Settings Modal Overlay
      'conn_8': {
        id: 'conn_8',
        sourceNodeId: s5SettingsTriggerBtnId,
        sourceEvent: 'on-click',
        action: 'open-overlay',
        destinationNodeId: screen6Id,
        overlay: {
          position: 'center',
          backdropEnabled: true,
          backdropColor: 'rgba(0,0,0,0.65)',
          backdropOpacity: 65,
          closeOnOutsideClick: true,
          closeOnEscape: true,
        },
        enabled: true,
      },
      // 9. Modal Overlay Close
      'conn_9': {
        id: 'conn_9',
        sourceNodeId: s6CloseBtnId,
        sourceEvent: 'on-click',
        action: 'close-overlay',
        enabled: true,
      },
    },
    interactions: {
      [s1CtaBtnId]: [
        {
          id: 'int_1',
          sourceNodeId: s1CtaBtnId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen2Id,
          transition: { type: 'slide-in', duration: 300, easing: 'ease-out', direction: 'left' },
          enabled: true,
        },
      ],
      [s1NavLinkFeaturesId]: [
        {
          id: 'int_2',
          sourceNodeId: s1NavLinkFeaturesId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen2Id,
          transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
          enabled: true,
        },
      ],
      [s1NavLinkPricingId]: [
        {
          id: 'int_3',
          sourceNodeId: s1NavLinkPricingId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen3Id,
          transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
          enabled: true,
        },
      ],
      [s1NavLinkLoginId]: [
        {
          id: 'int_4',
          sourceNodeId: s1NavLinkLoginId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen4Id,
          transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
          enabled: true,
        },
      ],
      [s2BackBtnId]: [
        {
          id: 'int_back_2',
          sourceNodeId: s2BackBtnId,
          trigger: 'on-click',
          action: 'back',
          enabled: true,
        },
      ],
      [s2CtaPricingId]: [
        {
          id: 'int_5',
          sourceNodeId: s2CtaPricingId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen3Id,
          transition: { type: 'slide-in', duration: 300, easing: 'ease-out', direction: 'left' },
          enabled: true,
        },
      ],
      [s3BackBtnId]: [
        {
          id: 'int_back_3',
          sourceNodeId: s3BackBtnId,
          trigger: 'on-click',
          action: 'back',
          enabled: true,
        },
      ],
      [s3GetStartedBtnId]: [
        {
          id: 'int_6',
          sourceNodeId: s3GetStartedBtnId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen4Id,
          transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
          enabled: true,
        },
      ],
      [s4SubmitBtnId]: [
        {
          id: 'int_7',
          sourceNodeId: s4SubmitBtnId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen5Id,
          transition: { type: 'smart-animate', duration: 300, easing: 'ease-out' },
          enabled: true,
        },
      ],
      [s4BackToHomeId]: [
        {
          id: 'int_back_4',
          sourceNodeId: s4BackToHomeId,
          trigger: 'on-click',
          action: 'navigate-to',
          destinationNodeId: screen1Id,
          transition: { type: 'dissolve', duration: 300, easing: 'ease-out' },
          enabled: true,
        },
      ],
      [s5SettingsTriggerBtnId]: [
        {
          id: 'int_8',
          sourceNodeId: s5SettingsTriggerBtnId,
          trigger: 'on-click',
          action: 'open-overlay',
          destinationNodeId: screen6Id,
          overlay: {
            position: 'center',
            backdropEnabled: true,
            backdropColor: 'rgba(0,0,0,0.65)',
            backdropOpacity: 65,
            closeOnOutsideClick: true,
            closeOnEscape: true,
          },
          enabled: true,
        },
      ],
      [s6CloseBtnId]: [
        {
          id: 'int_9',
          sourceNodeId: s6CloseBtnId,
          trigger: 'on-click',
          action: 'close-overlay',
          enabled: true,
        },
      ],
    },
    variables: {
      'pvar_is_logged_in': {
        id: 'pvar_is_logged_in',
        name: 'isLoggedIn',
        type: 'boolean',
        defaultValue: false,
      },
      'pvar_cart_count': {
        id: 'pvar_cart_count',
        name: 'cartCount',
        type: 'number',
        defaultValue: 0,
      },
    },
    settings: {
      devicePreset: 'desktop',
      customWidth: 1440,
      customHeight: 900,
      showHotspots: true,
      theme: 'dark',
    },
  };

  const initialPage: Page = recomputePageLayout({
    id: page1Id,
    name: '❖ Design System & Connected Prototype Screens',
    objects,
  });

  return {
    version: CURRENT_DOCUMENT_VERSION,
    id: generateId('doc'),
    name: 'BANAVA Interactive Prototype & App',
    pages: [initialPage],
    activePageId: page1Id,
    components,
    componentSets,
    styles: defaultStyles,
    variables: defaultVars,
    prototype: defaultPrototype,
    assets: {},
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}
