import type {
  DocumentModel,
  Page,
  FrameObject,
  TextObject,
  RectangleObject,
  ComponentInstanceObject,
  ComponentDefinition,
  ComponentSet,
  SceneObject,
} from '../types/document';
import { generateId } from '../utils/id';
import { recomputePageLayout } from '../layout/layoutEngine';
import { createDefaultStyles } from '../system/styleEngine';
import { createDefaultVariables } from '../system/variableEngine';

export const CURRENT_DOCUMENT_VERSION = 4;

export function createDefaultDocument(): DocumentModel {
  const page1Id = generateId('page');
  const defaultStyles = createDefaultStyles();
  const defaultVars = createDefaultVariables();

  const components: Record<string, ComponentDefinition> = {};
  const componentSets: Record<string, ComponentSet> = {};
  const objects: SceneObject[] = [];

  // ==========================================
  // 1. BUTTON COMPONENT SET (Primary, Secondary, Destructive)
  // ==========================================
  const btnSetId = 'set_button';
  const btnPrimaryId = 'comp_btn_primary';
  const btnSecondaryId = 'comp_btn_secondary';
  const btnDestructiveId = 'comp_btn_destructive';

  const btnPrimaryRootId = generateId('frame');
  const btnPrimaryLabelId = generateId('text');
  const btnSecondaryRootId = generateId('frame');
  const btnSecondaryLabelId = generateId('text');
  const btnDestructiveRootId = generateId('frame');
  const btnDestructiveLabelId = generateId('text');

  // Master: Primary Button
  const masterBtnPrimary: FrameObject = {
    id: btnPrimaryRootId,
    name: 'Button / Primary',
    type: 'frame',
    x: 80,
    y: 120,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: btnPrimaryId,
    fill: '#6366f1',
    fillVariableId: 'var_brand_primary',
    fillStyleId: 'style_color_primary',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const masterBtnPrimaryLabel: TextObject = {
    id: btnPrimaryLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 60,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: btnPrimaryRootId,
    content: 'Get Started',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  // Master: Secondary Button
  const masterBtnSecondary: FrameObject = {
    id: btnSecondaryRootId,
    name: 'Button / Secondary',
    type: 'frame',
    x: 240,
    y: 120,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: btnSecondaryId,
    fill: '#1e293b',
    stroke: '#334155',
    strokeWidth: 1,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const masterBtnSecondaryLabel: TextObject = {
    id: btnSecondaryLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 60,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: btnSecondaryRootId,
    content: 'Learn More',
    fontSize: 14,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#f8fafc',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  // Master: Destructive Button
  const masterBtnDestructive: FrameObject = {
    id: btnDestructiveRootId,
    name: 'Button / Destructive',
    type: 'frame',
    x: 400,
    y: 120,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: btnDestructiveId,
    fill: '#ef4444',
    fillStyleId: 'style_color_danger',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const masterBtnDestructiveLabel: TextObject = {
    id: btnDestructiveLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 60,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: btnDestructiveRootId,
    content: 'Delete',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  components[btnPrimaryId] = {
    id: btnPrimaryId,
    name: 'Button / Primary',
    category: 'Buttons',
    rootObjectId: btnPrimaryRootId,
    componentSetId: btnSetId,
    variantProperties: { Variant: 'Primary' },
    exposedProperties: [
      {
        id: 'prop_btn_p_label',
        name: 'Label',
        type: 'text',
        defaultValue: 'Get Started',
        targetLayerId: btnPrimaryLabelId,
        targetProperty: 'content',
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  components[btnSecondaryId] = {
    id: btnSecondaryId,
    name: 'Button / Secondary',
    category: 'Buttons',
    rootObjectId: btnSecondaryRootId,
    componentSetId: btnSetId,
    variantProperties: { Variant: 'Secondary' },
    exposedProperties: [
      {
        id: 'prop_btn_s_label',
        name: 'Label',
        type: 'text',
        defaultValue: 'Learn More',
        targetLayerId: btnSecondaryLabelId,
        targetProperty: 'content',
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  components[btnDestructiveId] = {
    id: btnDestructiveId,
    name: 'Button / Destructive',
    category: 'Buttons',
    rootObjectId: btnDestructiveRootId,
    componentSetId: btnSetId,
    variantProperties: { Variant: 'Destructive' },
    exposedProperties: [
      {
        id: 'prop_btn_d_label',
        name: 'Label',
        type: 'text',
        defaultValue: 'Delete',
        targetLayerId: btnDestructiveLabelId,
        targetProperty: 'content',
      },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  componentSets[btnSetId] = {
    id: btnSetId,
    name: 'Button',
    category: 'Buttons',
    variantPropertyNames: ['Variant'],
    componentIds: [btnPrimaryId, btnSecondaryId, btnDestructiveId],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  // ==========================================
  // 2. INPUT COMPONENT SET (Default, Focus, Error, Disabled)
  // ==========================================
  const inputSetId = 'set_input';
  const inputDefaultId = 'comp_input_default';
  const inputFocusId = 'comp_input_focus';
  const inputErrorId = 'comp_input_error';
  const inputDisabledId = 'comp_input_disabled';

  const inputDefaultRootId = generateId('frame');
  const inputDefaultTextId = generateId('text');
  const inputFocusRootId = generateId('frame');
  const inputFocusTextId = generateId('text');
  const inputErrorRootId = generateId('frame');
  const inputErrorTextId = generateId('text');
  const inputDisabledRootId = generateId('frame');
  const inputDisabledTextId = generateId('text');

  // Default Input Master
  const masterInputDefault: FrameObject = {
    id: inputDefaultRootId,
    name: 'Input / Default',
    type: 'frame',
    x: 80,
    y: 200,
    width: 220,
    height: 42,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: inputDefaultId,
    fill: '#181e2e',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'center',
    padding: { top: 8, right: 14, bottom: 8, left: 14 },
    itemSpacing: 8,
  };
  const masterInputDefaultText: TextObject = {
    id: inputDefaultTextId,
    name: 'Placeholder',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 20,
    rotation: 0,
    opacity: 60,
    visible: true,
    locked: false,
    parentId: inputDefaultRootId,
    content: 'Enter your email...',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  // Focus Input Master
  const masterInputFocus: FrameObject = {
    id: inputFocusRootId,
    name: 'Input / Focus',
    type: 'frame',
    x: 320,
    y: 200,
    width: 220,
    height: 42,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: inputFocusId,
    fill: '#181e2e',
    stroke: '#6366f1',
    strokeWidth: 2,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'center',
    padding: { top: 8, right: 14, bottom: 8, left: 14 },
    itemSpacing: 8,
  };
  const masterInputFocusText: TextObject = {
    id: inputFocusTextId,
    name: 'Value',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: inputFocusRootId,
    content: 'user@example.com',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#f8fafc',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  // Error Input Master
  const masterInputError: FrameObject = {
    id: inputErrorRootId,
    name: 'Input / Error',
    type: 'frame',
    x: 560,
    y: 200,
    width: 220,
    height: 42,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: inputErrorId,
    fill: '#181e2e',
    stroke: '#ef4444',
    strokeWidth: 1.5,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'center',
    padding: { top: 8, right: 14, bottom: 8, left: 14 },
    itemSpacing: 8,
  };
  const masterInputErrorText: TextObject = {
    id: inputErrorTextId,
    name: 'Error Text',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: inputErrorRootId,
    content: 'Invalid email address',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#f87171',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  // Disabled Input Master
  const masterInputDisabled: FrameObject = {
    id: inputDisabledRootId,
    name: 'Input / Disabled',
    type: 'frame',
    x: 800,
    y: 200,
    width: 220,
    height: 42,
    rotation: 0,
    opacity: 50,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: inputDisabledId,
    fill: '#0f172a',
    stroke: '#1e293b',
    strokeWidth: 1,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'center',
    padding: { top: 8, right: 14, bottom: 8, left: 14 },
    itemSpacing: 8,
  };
  const masterInputDisabledText: TextObject = {
    id: inputDisabledTextId,
    name: 'Disabled Text',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: inputDisabledRootId,
    content: 'Read-only field',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#64748b',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  components[inputDefaultId] = {
    id: inputDefaultId,
    name: 'Input / Default',
    category: 'Inputs',
    rootObjectId: inputDefaultRootId,
    componentSetId: inputSetId,
    variantProperties: { State: 'Default' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  components[inputFocusId] = {
    id: inputFocusId,
    name: 'Input / Focus',
    category: 'Inputs',
    rootObjectId: inputFocusRootId,
    componentSetId: inputSetId,
    variantProperties: { State: 'Focus' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  components[inputErrorId] = {
    id: inputErrorId,
    name: 'Input / Error',
    category: 'Inputs',
    rootObjectId: inputErrorRootId,
    componentSetId: inputSetId,
    variantProperties: { State: 'Error' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  components[inputDisabledId] = {
    id: inputDisabledId,
    name: 'Input / Disabled',
    category: 'Inputs',
    rootObjectId: inputDisabledRootId,
    componentSetId: inputSetId,
    variantProperties: { State: 'Disabled' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  componentSets[inputSetId] = {
    id: inputSetId,
    name: 'Input Field',
    category: 'Inputs',
    variantPropertyNames: ['State'],
    componentIds: [inputDefaultId, inputFocusId, inputErrorId, inputDisabledId],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  // ==========================================
  // 3. CARDS (Product Card & Profile Card)
  // ==========================================
  const cardSetId = 'set_cards';
  const cardProductId = 'comp_card_product';
  const cardProfileId = 'comp_card_profile';

  const cardProductRootId = generateId('frame');
  const cardProductBadgeId = generateId('frame');
  const cardProductBadgeTextId = generateId('text');
  const cardProductTitleId = generateId('text');
  const cardProductDescId = generateId('text');

  const masterCardProduct: FrameObject = {
    id: cardProductRootId,
    name: 'Card / Product Card',
    type: 'frame',
    x: 80,
    y: 280,
    width: 280,
    height: 180,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: cardProductId,
    fill: '#181e2e',
    fillVariableId: 'var_card_surface',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'stretch',
    padding: { top: 20, right: 20, bottom: 20, left: 20 },
    itemSpacing: 12,
  };
  const masterCardProductBadge: FrameObject = {
    id: cardProductBadgeId,
    name: 'Badge',
    type: 'frame',
    x: 0,
    y: 0,
    width: 60,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardProductRootId,
    fill: 'rgba(99, 102, 241, 0.15)',
    cornerRadius: 6,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 2, right: 8, bottom: 2, left: 8 },
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const masterCardProductBadgeText: TextObject = {
    id: cardProductBadgeTextId,
    name: 'Badge Text',
    type: 'text',
    x: 0,
    y: 0,
    width: 40,
    height: 16,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardProductBadgeId,
    content: 'PRO',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const masterCardProductTitle: TextObject = {
    id: cardProductTitleId,
    name: 'Product Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 240,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardProductRootId,
    content: 'Enterprise Architecture',
    fontSize: 16,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const masterCardProductDesc: TextObject = {
    id: cardProductDescId,
    name: 'Description',
    type: 'text',
    x: 0,
    y: 0,
    width: 240,
    height: 38,
    rotation: 0,
    opacity: 75,
    visible: true,
    locked: false,
    parentId: cardProductRootId,
    content: 'Scalable cloud workflows and real-time design systems.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'left',
    lineHeight: 1.4,
    letterSpacing: 0,
    autoResize: 'fixed',
  };

  components[cardProductId] = {
    id: cardProductId,
    name: 'Card / Product Card',
    category: 'Cards',
    rootObjectId: cardProductRootId,
    componentSetId: cardSetId,
    variantProperties: { Type: 'Product' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  // Profile Card Master
  const cardProfileRootId = generateId('frame');
  const cardProfileAvatarId = generateId('rect');
  const cardProfileNameId = generateId('text');
  const cardProfileRoleId = generateId('text');

  const masterCardProfile: FrameObject = {
    id: cardProfileRootId,
    name: 'Card / Profile Card',
    type: 'frame',
    x: 400,
    y: 280,
    width: 280,
    height: 180,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: cardProfileId,
    fill: '#181e2e',
    fillVariableId: 'var_card_surface',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 20, right: 20, bottom: 20, left: 20 },
    itemSpacing: 10,
  };
  const masterCardProfileAvatar: RectangleObject = {
    id: cardProfileAvatarId,
    name: 'Avatar',
    type: 'rectangle',
    x: 0,
    y: 0,
    width: 48,
    height: 48,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardProfileRootId,
    fill: '#6366f1',
    cornerRadius: 24,
  };
  const masterCardProfileName: TextObject = {
    id: cardProfileNameId,
    name: 'Name',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardProfileRootId,
    content: 'Sagar Murkute',
    fontSize: 15,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const masterCardProfileRole: TextObject = {
    id: cardProfileRoleId,
    name: 'Role',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 18,
    rotation: 0,
    opacity: 70,
    visible: true,
    locked: false,
    parentId: cardProfileRootId,
    content: 'Principal Designer',
    fontSize: 12,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  components[cardProfileId] = {
    id: cardProfileId,
    name: 'Card / Profile Card',
    category: 'Cards',
    rootObjectId: cardProfileRootId,
    componentSetId: cardSetId,
    variantProperties: { Type: 'Profile' },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  componentSets[cardSetId] = {
    id: cardSetId,
    name: 'Card Component',
    category: 'Cards',
    variantPropertyNames: ['Type'],
    componentIds: [cardProductId, cardProfileId],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  // ==========================================
  // 4. NAVIGATION (Header Component)
  // ==========================================
  const headerCompId = 'comp_nav_header';
  const headerRootId = generateId('frame');
  const headerLogoId = generateId('text');
  const headerLinksId = generateId('text');

  const masterHeader: FrameObject = {
    id: headerRootId,
    name: 'Navigation / Header',
    type: 'frame',
    x: 80,
    y: 500,
    width: 900,
    height: 64,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    isComponent: true,
    componentId: headerCompId,
    fill: '#181e2e',
    fillVariableId: 'var_card_surface',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 12,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'center',
    padding: { top: 14, right: 24, bottom: 14, left: 24 },
    itemSpacing: 16,
    sizingHorizontal: 'fixed',
    sizingVertical: 'hug',
  };
  const masterHeaderLogo: TextObject = {
    id: headerLogoId,
    name: 'Logo',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: headerRootId,
    content: '❖ BANAVA DESIGN',
    fontSize: 16,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const masterHeaderLinks: TextObject = {
    id: headerLinksId,
    name: 'Nav Links',
    type: 'text',
    x: 0,
    y: 0,
    width: 280,
    height: 20,
    rotation: 0,
    opacity: 80,
    visible: true,
    locked: false,
    parentId: headerRootId,
    content: 'Components    Styles    Variables    Docs',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#cbd5e1',
    textAlign: 'right',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  components[headerCompId] = {
    id: headerCompId,
    name: 'Navigation / Header',
    category: 'Navigation',
    rootObjectId: headerRootId,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };

  // Collect all Master scene objects
  objects.push(
    masterBtnPrimary,
    masterBtnPrimaryLabel,
    masterBtnSecondary,
    masterBtnSecondaryLabel,
    masterBtnDestructive,
    masterBtnDestructiveLabel,
    masterInputDefault,
    masterInputDefaultText,
    masterInputFocus,
    masterInputFocusText,
    masterInputError,
    masterInputErrorText,
    masterInputDisabled,
    masterInputDisabledText,
    masterCardProduct,
    masterCardProductBadge,
    masterCardProductBadgeText,
    masterCardProductTitle,
    masterCardProductDesc,
    masterCardProfile,
    masterCardProfileAvatar,
    masterCardProfileName,
    masterCardProfileRole,
    masterHeader,
    masterHeaderLogo,
    masterHeaderLinks
  );

  // ==========================================
  // 5. LIVE DEMO LANDING PAGE (Assembled entirely from Component Instances!)
  // ==========================================
  const landingPageFrameId = generateId('frame');
  const heroSectionId = generateId('frame');
  const heroHeadingId = generateId('text');
  const heroSubheadingId = generateId('text');
  const heroBtnGroupId = generateId('frame');
  const cardsGridId = generateId('frame');

  // Root Landing Page Frame
  const landingPageFrame: FrameObject = {
    id: landingPageFrameId,
    name: 'Live Landing Page (Component Driven)',
    type: 'frame',
    x: 1040,
    y: 80,
    width: 960,
    height: 860,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: null,
    fill: '#0f131c',
    fillVariableId: 'var_bg_surface',
    stroke: '#222938',
    strokeWidth: 1,
    cornerRadius: 16,
    clipsContent: true,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'stretch',
    padding: { top: 32, right: 32, bottom: 32, left: 32 },
    itemSpacing: 32,
    sizingHorizontal: 'fixed',
    sizingVertical: 'hug',
  };

  // Header Instance inside Landing Page
  const instHeaderId = generateId('inst');
  const instHeaderChildLogoId = generateId('text');
  const instHeaderChildLinksId = generateId('text');
  const instHeader: ComponentInstanceObject = {
    id: instHeaderId,
    name: 'Header Instance',
    type: 'instance',
    x: 0,
    y: 0,
    width: 896,
    height: 64,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: landingPageFrameId,
    componentId: headerCompId,
    fill: '#181e2e',
    fillVariableId: 'var_card_surface',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 12,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'center',
    padding: { top: 14, right: 24, bottom: 14, left: 24 },
    itemSpacing: 16,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const instHeaderLogo: TextObject = {
    id: instHeaderChildLogoId,
    name: 'Logo',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instHeaderId,
    masterObjectId: headerLogoId,
    content: '❖ BANAVA LIVE',
    fontSize: 16,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const instHeaderLinks: TextObject = {
    id: instHeaderChildLinksId,
    name: 'Nav Links',
    type: 'text',
    x: 0,
    y: 0,
    width: 280,
    height: 20,
    rotation: 0,
    opacity: 80,
    visible: true,
    locked: false,
    parentId: instHeaderId,
    masterObjectId: headerLinksId,
    content: 'Components    Styles    Variables    Docs',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#cbd5e1',
    textAlign: 'right',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  // Hero Section Frame
  const heroSection: FrameObject = {
    id: heroSectionId,
    name: 'Hero Content',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 220,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: landingPageFrameId,
    fill: 'transparent',
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 24, right: 0, bottom: 24, left: 0 },
    itemSpacing: 16,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const heroHeading: TextObject = {
    id: heroHeadingId,
    name: 'Hero Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 600,
    height: 48,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: heroSectionId,
    content: 'Design Systems Reimagined',
    fontSize: 36,
    fontWeight: 800,
    fontFamily: 'Outfit, Inter, sans-serif',
    fill: '#ffffff',
    fillVariableId: 'var_text_primary',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: -0.5,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const heroSubheading: TextObject = {
    id: heroSubheadingId,
    name: 'Hero Subtitle',
    type: 'text',
    x: 0,
    y: 0,
    width: 540,
    height: 40,
    rotation: 0,
    opacity: 80,
    visible: true,
    locked: false,
    parentId: heroSectionId,
    content: 'Reusable components, live tokens, style inheritance, and instant variant switching in BANAVA.',
    fontSize: 15,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    fillVariableId: 'var_text_secondary',
    textAlign: 'center',
    lineHeight: 1.4,
    letterSpacing: 0,
    autoResize: 'fixed',
    sizingHorizontal: 'fixed',
    sizingVertical: 'hug',
  };

  // Hero Button Group Frame
  const heroBtnGroup: FrameObject = {
    id: heroBtnGroupId,
    name: 'Hero Action Buttons',
    type: 'frame',
    x: 0,
    y: 0,
    width: 320,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: heroSectionId,
    fill: 'transparent',
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    itemSpacing: 16,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  // Instance of Primary Button (with override: 'Explore System')
  const instHeroBtnPrimaryId = generateId('inst');
  const instHeroBtnPrimaryChildLabelId = generateId('text');
  const instHeroBtnPrimary: ComponentInstanceObject = {
    id: instHeroBtnPrimaryId,
    name: 'Primary Button Instance',
    type: 'instance',
    x: 0,
    y: 0,
    width: 160,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: heroBtnGroupId,
    componentId: btnPrimaryId,
    variantProperties: { Variant: 'Primary' },
    overrides: {
      [btnPrimaryLabelId]: { content: 'Explore System' },
    },
    fill: '#6366f1',
    fillVariableId: 'var_brand_primary',
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const instHeroBtnPrimaryLabel: TextObject = {
    id: instHeroBtnPrimaryChildLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 100,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instHeroBtnPrimaryId,
    masterObjectId: btnPrimaryLabelId,
    content: 'Explore System',
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  // Instance of Secondary Button (with override: 'Documentation')
  const instHeroBtnSecId = generateId('inst');
  const instHeroBtnSecChildLabelId = generateId('text');
  const instHeroBtnSec: ComponentInstanceObject = {
    id: instHeroBtnSecId,
    name: 'Secondary Button Instance',
    type: 'instance',
    x: 0,
    y: 0,
    width: 140,
    height: 44,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: heroBtnGroupId,
    componentId: btnSecondaryId,
    variantProperties: { Variant: 'Secondary' },
    overrides: {
      [btnSecondaryLabelId]: { content: 'Documentation' },
    },
    fill: '#1e293b',
    stroke: '#334155',
    strokeWidth: 1,
    cornerRadius: 8,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 10, right: 18, bottom: 10, left: 18 },
    itemSpacing: 8,
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const instHeroBtnSecLabel: TextObject = {
    id: instHeroBtnSecChildLabelId,
    name: 'Label',
    type: 'text',
    x: 0,
    y: 0,
    width: 90,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instHeroBtnSecId,
    masterObjectId: btnSecondaryLabelId,
    content: 'Documentation',
    fontSize: 14,
    fontWeight: 500,
    fontFamily: 'Inter, sans-serif',
    fill: '#f8fafc',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };

  // Cards Grid Frame
  const cardsGrid: FrameObject = {
    id: cardsGridId,
    name: 'Cards Row',
    type: 'frame',
    x: 0,
    y: 0,
    width: 896,
    height: 220,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: landingPageFrameId,
    fill: 'transparent',
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'space-between',
    counterAxisAlignItems: 'stretch',
    padding: { top: 0, right: 0, bottom: 0, left: 0 },
    itemSpacing: 24,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };

  // Product Card Instance 1
  const instCard1Id = generateId('inst');
  const instCard1BadgeId = generateId('frame');
  const instCard1BadgeTextId = generateId('text');
  const instCard1TitleId = generateId('text');
  const instCard1DescId = generateId('text');

  const instCard1: ComponentInstanceObject = {
    id: instCard1Id,
    name: 'Product Card Instance 1',
    type: 'instance',
    x: 0,
    y: 0,
    width: 280,
    height: 180,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardsGridId,
    componentId: cardProductId,
    fill: '#181e2e',
    fillVariableId: 'var_card_surface',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'stretch',
    padding: { top: 20, right: 20, bottom: 20, left: 20 },
    itemSpacing: 12,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const instCard1Badge: FrameObject = {
    id: instCard1BadgeId,
    name: 'Badge',
    type: 'frame',
    x: 0,
    y: 0,
    width: 60,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard1Id,
    masterObjectId: cardProductBadgeId,
    fill: 'rgba(99, 102, 241, 0.15)',
    cornerRadius: 6,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 2, right: 8, bottom: 2, left: 8 },
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const instCard1BadgeText: TextObject = {
    id: instCard1BadgeTextId,
    name: 'Badge Text',
    type: 'text',
    x: 0,
    y: 0,
    width: 40,
    height: 16,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard1BadgeId,
    masterObjectId: cardProductBadgeTextId,
    content: 'CORE',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#818cf8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const instCard1Title: TextObject = {
    id: instCard1TitleId,
    name: 'Product Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 240,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard1Id,
    masterObjectId: cardProductTitleId,
    content: 'Design Variables',
    fontSize: 16,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const instCard1Desc: TextObject = {
    id: instCard1DescId,
    name: 'Description',
    type: 'text',
    x: 0,
    y: 0,
    width: 240,
    height: 38,
    rotation: 0,
    opacity: 75,
    visible: true,
    locked: false,
    parentId: instCard1Id,
    masterObjectId: cardProductDescId,
    content: 'Switch dark and light modes with instant variable cascade.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'left',
    lineHeight: 1.4,
    letterSpacing: 0,
    autoResize: 'fixed',
  };

  // Product Card Instance 2
  const instCard2Id = generateId('inst');
  const instCard2BadgeId = generateId('frame');
  const instCard2BadgeTextId = generateId('text');
  const instCard2TitleId = generateId('text');
  const instCard2DescId = generateId('text');

  const instCard2: ComponentInstanceObject = {
    id: instCard2Id,
    name: 'Product Card Instance 2',
    type: 'instance',
    x: 0,
    y: 0,
    width: 280,
    height: 180,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardsGridId,
    componentId: cardProductId,
    fill: '#181e2e',
    fillVariableId: 'var_card_surface',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'start',
    counterAxisAlignItems: 'stretch',
    padding: { top: 20, right: 20, bottom: 20, left: 20 },
    itemSpacing: 12,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const instCard2Badge: FrameObject = {
    id: instCard2BadgeId,
    name: 'Badge',
    type: 'frame',
    x: 0,
    y: 0,
    width: 60,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard2Id,
    masterObjectId: cardProductBadgeId,
    fill: 'rgba(16, 185, 129, 0.15)',
    cornerRadius: 6,
    layoutMode: 'horizontal',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 2, right: 8, bottom: 2, left: 8 },
    sizingHorizontal: 'hug',
    sizingVertical: 'hug',
  };
  const instCard2BadgeText: TextObject = {
    id: instCard2BadgeTextId,
    name: 'Badge Text',
    type: 'text',
    x: 0,
    y: 0,
    width: 40,
    height: 16,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard2BadgeId,
    masterObjectId: cardProductBadgeTextId,
    content: 'FAST',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: 'Inter, sans-serif',
    fill: '#34d399',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const instCard2Title: TextObject = {
    id: instCard2TitleId,
    name: 'Product Title',
    type: 'text',
    x: 0,
    y: 0,
    width: 240,
    height: 24,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard2Id,
    masterObjectId: cardProductTitleId,
    content: 'Variant Switching',
    fontSize: 16,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const instCard2Desc: TextObject = {
    id: instCard2DescId,
    name: 'Description',
    type: 'text',
    x: 0,
    y: 0,
    width: 240,
    height: 38,
    rotation: 0,
    opacity: 75,
    visible: true,
    locked: false,
    parentId: instCard2Id,
    masterObjectId: cardProductDescId,
    content: 'Switch between primary, secondary, and destructive states effortlessly.',
    fontSize: 13,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'left',
    lineHeight: 1.4,
    letterSpacing: 0,
    autoResize: 'fixed',
  };

  // Profile Card Instance
  const instCard3Id = generateId('inst');
  const instCard3AvatarId = generateId('rect');
  const instCard3NameId = generateId('text');
  const instCard3RoleId = generateId('text');

  const instCard3: ComponentInstanceObject = {
    id: instCard3Id,
    name: 'Profile Card Instance',
    type: 'instance',
    x: 0,
    y: 0,
    width: 280,
    height: 180,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: cardsGridId,
    componentId: cardProfileId,
    fill: '#181e2e',
    fillVariableId: 'var_card_surface',
    stroke: '#2b3548',
    strokeWidth: 1,
    cornerRadius: 12,
    layoutMode: 'vertical',
    primaryAxisAlignItems: 'center',
    counterAxisAlignItems: 'center',
    padding: { top: 20, right: 20, bottom: 20, left: 20 },
    itemSpacing: 10,
    sizingHorizontal: 'fill',
    sizingVertical: 'hug',
  };
  const instCard3Avatar: RectangleObject = {
    id: instCard3AvatarId,
    name: 'Avatar',
    type: 'rectangle',
    x: 0,
    y: 0,
    width: 48,
    height: 48,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard3Id,
    masterObjectId: cardProfileAvatarId,
    fill: '#6366f1',
    cornerRadius: 24,
  };
  const instCard3Name: TextObject = {
    id: instCard3NameId,
    name: 'Name',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 20,
    rotation: 0,
    opacity: 100,
    visible: true,
    locked: false,
    parentId: instCard3Id,
    masterObjectId: cardProfileNameId,
    content: 'Alex Rivera',
    fontSize: 15,
    fontWeight: 600,
    fontFamily: 'Inter, sans-serif',
    fill: '#ffffff',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };
  const instCard3Role: TextObject = {
    id: instCard3RoleId,
    name: 'Role',
    type: 'text',
    x: 0,
    y: 0,
    width: 140,
    height: 18,
    rotation: 0,
    opacity: 70,
    visible: true,
    locked: false,
    parentId: instCard3Id,
    masterObjectId: cardProfileRoleId,
    content: 'Lead System Architect',
    fontSize: 12,
    fontWeight: 400,
    fontFamily: 'Inter, sans-serif',
    fill: '#94a3b8',
    textAlign: 'center',
    lineHeight: 1.2,
    letterSpacing: 0,
    autoResize: 'auto-width',
  };

  // Add Landing Page and its component instances to scene objects
  objects.push(
    landingPageFrame,
    instHeader,
    instHeaderLogo,
    instHeaderLinks,
    heroSection,
    heroHeading,
    heroSubheading,
    heroBtnGroup,
    instHeroBtnPrimary,
    instHeroBtnPrimaryLabel,
    instHeroBtnSec,
    instHeroBtnSecLabel,
    cardsGrid,
    instCard1,
    instCard1Badge,
    instCard1BadgeText,
    instCard1Title,
    instCard1Desc,
    instCard2,
    instCard2Badge,
    instCard2BadgeText,
    instCard2Title,
    instCard2Desc,
    instCard3,
    instCard3Avatar,
    instCard3Name,
    instCard3Role
  );

  const initialPage: Page = recomputePageLayout({
    id: page1Id,
    name: '❖ Design System & Landing Page',
    objects,
  });

  return {
    version: CURRENT_DOCUMENT_VERSION,
    id: generateId('doc'),
    name: 'BANAVA Design System & App',
    pages: [initialPage],
    activePageId: page1Id,
    components,
    componentSets,
    styles: defaultStyles,
    variables: defaultVars,
    assets: {},
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}
